[package]
name = "vector3d"
version = "0.1.0"
authors = ["Isaac <isaachill13@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fast_inv_sqrt = "1.0.1"